### ISSUE TITLE
older button is error

### ISSUE THREAD

**Issue by langyapojun** [SamWhited/typo#29]
http://langyapojun.github.io/
the button older is error,how should i fixed and change it???

**Comment by SamWhited** [comment]
Interesting; I cannot reproduce this problem. It appears that you have more pages in your archive than on your main site. Have you made any modifications to the theme, or done anything else odd to make that happen?

**Comment by langyapojun** [comment]
[https://github.com/langyapojun/langyapojun.github.io](https://github.com/langyapojun/langyapojun.github.io)
that is my blog generate source;
and .yml file

**Comment by SamWhited** [comment]
What about the source itself (not the generated blog, the actual source)?

I suspect something in there is messing things up.

**Comment by langyapojun** [comment]
https://github.com/langyapojun/octopress-source
i upload my source in github,please help me to fix it,thx!!

**Comment by SamWhited** [comment]
You don't appear to have the pagination plugin installed at all (maybe it's a later version of Octopress that's not supported by this theme, or something). I'm afraid this isn't really something I can help with.

**Comment by langyapojun** [comment]
OK，THX
