### ISSUE TITLE
[Guide required] Blog does not look like yours. :-(

### ISSUE THREAD

**Issue by Drakedogs** [SamWhited/typo#30]
Hi Sam,

first of all I'd like to thank you for sharing this beautiful theme with us! :) I have installed it yesterday, but my blog does not look like yours. :( (e.g. I do not have those circles / squares) I just have got big pictures.

Would it be possible to write a guide for new users? :) Do I need to rewrite any configuration file(s)?

My post layout looks as followed:

```
---
layout: post
title: "Hello World!"
date: 2015-11-08 09:46:14 +0100
comments: true
categories: test 
---
Testing 123.
{% img http://placekitten.com/890/280 %}
```

Best regards

Spencer

**Comment by SamWhited** [comment]
Hi there, I'm glad you like the theme. Unfortunately, there's really not much I can do to help w/o any specifics of what's going wrong.

I'd take a look at the README, all of the config is documented there. You shouldn't have to do anything special to make it work, however, just add the various image config things to the post above (which shouldn't even be showing a big picture as it doesn't look like you've specified a picture at all).

This is really an issue tracker though, not a discussion forum. I'll see if I can't think up a better way to do support requests on this project.

If you find that there is an actual bug, feel free to file it here. Thanks!
